### PR TITLE
update criterion, add html_reports feature as suggested by criterion

### PR DESCRIPTION
**Pull request by zzlk**
[ci-bench]

### CODE REVIEW

**Comment by zzlk** [comment]
Seems as though they have deprcated the csv output option in criterion 4.0. Supposedly you can enable it with a cargo.toml feature but when you do that, criterion fails to build. So I guess it's completely unmaintained now. As far as I can tell, nothing is consuming the raw_csv output.

Other than that, the output format doesn't seem to be changed so I believe it should work.

**Comment by MingweiSamuel** [comment]
Hmm yeah nothing we do uses the CSV it looks like

**Comment by zzlk** [comment]
this should wait for: https://github.com/hydro-project/hydroflow/pull/335

**Comment by MingweiSamuel** [comment]
Ok #335 merged, rebase on main and lets see if anything noticeably breaks

**Comment by zzlk** [comment]
@MingweiSamuel looks like it passed, good to merge?

**Comment by MingweiSamuel** [comment]
Did a manual ci run, seems to have worked! 👌
image

**Pull request merged**
