### PR TITLE
Use `Slotmap` instead of `Vec` to store graph items

### PR DESCRIPTION
**Pull request by MingweiSamuel**

### CODE REVIEW

**Comment by justinj** [comment]
What is the reason for this change?

**Comment by MingweiSamuel** [comment]
Mainly want stable keys for metadata stuff with graphviz, it is a bit confusing when everything is a `Vec<_>` with indices

**Review by justinj — APPROVED** [review]
I still don't really see why the Slotmap achieves anything, isn't the point of it that it lets you re-use slots when deleting an entry, but we never delete stuff from these collections? I am just not super into moving away from a stdlib data structure to some library one when I don't really see the reason to, but if you think it will make the code more pleasant to write then I don't mind that much.

**Comment by MingweiSamuel** [comment]
I could also just make a thin wrapper around `Vec` which might be a bit better for performance

**Comment by jhellerstein** [comment]
I think that makes sens

**Pull request closed without merging**
