### PR TITLE
initial TopoloTree actor implementation for binary tree

### PR DESCRIPTION
**Pull request by conor-23**

### CODE REVIEW

**Comment by zzlk** [comment]
There's a lot of clippy complaints, you should run clippy locally and fix what it says first.

in the root of your repo:
```
cargo clippy --all-targets --all-features -- -D warnings
```
then fix what it complains about, then run it again until it's clean.

**Comment by jhellerstein** [comment]
You can also configure VSCode to run clippy for your Problems pane:
https://users.rust-lang.org/t/how-to-use-clippy-in-vs-code-with-rust-analyzer/41881

**Comment by zzlk** [comment]
This PR includes a merge commit that has mingwei's latest change in it, so it is confusing what your actual changes are vs mingwei's already-in-main changes. Can you rebase your PR on top of main so that it doesn't have the merge commit in it?

**Comment by shadaj** [comment]
Closed in favor of rebased #515

**Pull request closed without merging**
