### PR TITLE
Fix handling of warnings, degenerate merge and tee

### PR DESCRIPTION
**Pull request by MingweiSamuel**

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
Ideally in the future the degenerate tees and merges would be eliminated before codegen

**Review by jhellerstein — COMMENTED** [review]
Wow the error messages appear to be generated magically!

**Comment by MingweiSamuel** [comment]
@jhellerstein 

> Wow the error messages appear to be generated magically!

Oh yeah, they show up in the PR UI :)

**Comment by jhellerstein** [comment]
What I'm saying is that I'm unclear what part of the code generates the
error text.

**Pull request merged**
