### PR TITLE
test(hydroflow): Change example tests to use localhost IP

### PR DESCRIPTION
**Pull request by MingweiSamuel**

### CODE REVIEW

**Review by zzlk — COMMENTED** [review]
why?

**Comment by MingweiSamuel** [comment]
127.0.0.100 isn't usually a valid localhost IP?

**Comment by zzlk** [comment]
> 127.0.0.100 isn't usually a valid localhost IP? Doesn't bind on my mac

I think anything 127.x.x.x should work cuz localhost should be 127.0.0.0/8

**Comment by MingweiSamuel** [comment]
seems like its just a apple thing https://github.com/akka/akka/issues/17084#issuecomment-93740603

**Comment by zzlk** [comment]
> seems like its just a apple thing https://github.com/akka/akka/issues/17084#issuecomment-93740603
> 
> https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x

oh, ok.

**Review by zzlk — APPROVED** [review]

**Pull request merged**
