### PR TITLE
Update lib.rs to emit diagnostics

### PR DESCRIPTION
**Pull request by amrita-rajan**

### CODE REVIEW

**Comment by shadaj** [comment]
Ooh hmm I am just realizing that we did make some significant changes to the internals of the macro entrypoint. You might just want to re-apply your changes by hand on top of the main branch, since it might be difficult to merge things now?

**Comment by jhellerstein** [comment]
Can we close this PR? @shadaj

**Comment by jhellerstein** [comment]
pinging you on this again @shadaj

**Comment by shadaj** [comment]
Closed in favor of #421

**Pull request closed without merging**
