### PR TITLE
make join default to multiset join

### PR DESCRIPTION
**Pull request by zzlk**

### CODE REVIEW

**Comment by zzlk** [comment]
fixed the reachability/un-reachability examples by adding in a unique() after the join. The mermaid was not updated.

**Review by MingweiSamuel — APPROVED** [review]

**Comment by zzlk** [comment]
should update join doc comment to demonstrate how it behves more clearly.

**Comment by zzlk** [comment]
waiting on https://github.com/hydro-project/hydroflow/pull/784

**Comment by zzlk** [comment]
Kind of need this https://github.com/hydro-project/hydroflow/issues/698 before this can be safely checked in because it is unclear which examples it would break. They use a lot of joins...

**Pull request merged**
