### PR TITLE
build: use different target dir for rust-analyzer to prevent thrashing with cargo

### PR DESCRIPTION
**Pull request by MingweiSamuel**
Might only be a problem on windows?

Edit: seems to only be windows

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
Hmm, this might use up more disk space for @jhellerstein

**Comment by shadaj** [comment]
Wouldn't disabling the python feature be sufficient to prevent thrashing?

**Comment by shadaj** [comment]
Maybe we should inspect all our `build.rs`, similar issues were happening in https://github.com/BLAKE3-team/BLAKE3/pull/413

**Comment by MingweiSamuel** [comment]
Just changed my user .vscode settings on my windows machine.

**Pull request closed without merging**
