### PR TITLE
add repeat_fn op

### PR DESCRIPTION
**Pull request by zzlk**

### CODE REVIEW

**Comment by zzlk** [comment]
I made this but I'm not sure if it's completely redundant with repeat_iter() -> map(). Maybe it's a bit different since the closure itself can have mutable state, like a counter or something.

Additionally, I'm not sure if the closure itself is stored in sensible place.

This was made to generate random number inputs for the kvs benchmark.

**Comment by MingweiSamuel** [comment]
Would be the same as `source_iter(std::iter::from_fn(|| { x += 1; Some(x) }).take(3))`, still good to have though

**Comment by zzlk** [comment]
> Would be the same as `source_iter(std::iter::from_fn(|| { x += 1; Some(x) }).take(3))`, still good to have though

hmm, I'll rewrite the op to re-use repeat_iter then.

**Comment by MingweiSamuel** [comment]
The `Some` part of it is annoying for that though

**Review by MingweiSamuel — APPROVED** [review]

**Pull request merged**
