### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by shadaj**
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/hydro-project/hydroflow/pull/1418).
* #1421
* __->__ #1418

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
Probably best to keep the non-breaking versions the same, or at least keep the minor versions, as a lower bound
```
1.2.3  :=  >=1.2.3, <2.0.0
1.2    :=  >=1.2.0, <2.0.0
1      :=  >=1.0.0, <2.0.0
```

**Comment by shadaj** [comment]
The algorithm I used for how much to drop was to use just major version when:
a) we aren't depending on some very low level internal detail of the library
b) the library has established practices for prevent breaking changes

For others it's major.minor.

**Comment by MingweiSamuel** [comment]
"the package `hydroflow` depends on `tokio-stream`, with features: `io-util` but `tokio-stream` does not have these features"
```
cargo +nightly -Zdirect-minimal-versions update
```
I'll go thru and find the minimal versions and add them to this PR

**Comment by MingweiSamuel** [comment]
#1423

**Pull request closed without merging**
